// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnswcpgdatxkrwbhlprq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhuc3djcGdkYXR4a3J3YmhscHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODQ5NTQsImV4cCI6MjA1NDM2MDk1NH0.AKxuTeVn0xNEdPg9CtJcMQYImoRlIc7spTw282L0SRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);